### PR TITLE
Login page backgroud and input text color changed as primary color

### PR DESCRIPTION
**Pull request by Ram-dev27**
Pull-Request for `paretOS`

## Description
- Updated Login.js file to changes the input text color and the label color
- removing the inline styles

## Relates to
- #166  or whichever ticket number the pr is addressing

## Reviewers
- @jayeclark 
- ...

### Screenshots / Login page
image

### CODE REVIEW

**Review by mikhael28 — CHANGES_REQUESTED** [review]
Hey @Ram-dev27 , thank you for sending this in! In this instance though, I don't think changing the text input to the primary color is a good idea - it's a bit of a UX anti-pattern, in the sense that most people when they think RED - means stop. Or broken. Having the text be red, might make the user think their input has been invalidated by some text validation logic.'
Additionally, from an accessibility perspective, by having the background be gray (not white) and the font red, the text becomes inherently difficult to read (though it might look cool!)

For those reasons, I'm going to ask that you have the background of the form be the color you chose in the screenshot you posted in the picture, and can you have the color of the text be black instead of red? 
Screen Shot 2022-04-07 at 4 18 38 PM

**Comment by jayeclark** [comment]
I think maybe there is some confusion about the original issue. It had asked for the text to be changed to the primary or secondary text color (text.primary or text.secondary) 
 of the theme (which is a white or very light gray) and for the background to be the paper color of the theme (a dark gray - the light background color I put in temporarily inline was just a bandaid). 

(I think maybe the ‘text’ part in the original issue got missed!)

The MUI default behavior is: show the text as the palette.primary color when the input is focused and the palette.text.primary color when not. @mikhael28 can you clarify - do you want the ‘palette.primary when focused’ to be overridden?

**Comment by mikhael28** [comment]
To clarify, let's have the text be text.primary!

**Comment by Ram-dev27** [comment]
@mikhael28 can I change the text input color default, like the following image
image
Is that expected one ?

**Comment by mikhael28** [comment]
@Ram-dev27 yes, that looks great! Go ahead and push up that change 🚀

**Comment by Ram-dev27** [comment]
I done the changes @mikhael28 you can check now :D

**Comment by mikhael28** [comment]
Sorry for the delay @Ram-dev27 - I'm merging in! Sorry for the delay. Tell us about yourself, what are your goals in programming? It looks like you are just starting on your journey!

**Comment by mikhael28** [comment]
Have you thought about picking up any other issues?

**Comment by Ram-dev27** [comment]
Hay @mikhael28 yup now only I start my working career in one startup company, I had completed BE in computer science engineering stream few months ago, my programming goals to learn the JavaScript( react and node JS) in depth to became the full stack developer. 🚀

**Comment by mikhael28** [comment]
That's great - @Ram-dev27 we have a 'developer-only' Discord account I'm happy to invite you to, what is the email you would prefer?

**Comment by Ram-dev27** [comment]
You can use ramachandran27271999@gmail.com Gmail account @mikhael28 , I happy to join with you guys :D

**Pull request merged**
