### PR TITLE
Refactored Signup forms: react-bootstrap -> react-hook-form migration

### PR DESCRIPTION
**Pull request by houssamboudiar**
Pull-Request for `paretOS`

Description
- Refactored Signup.tsx forms react-bootstrap -> react-hook-form migration
- Added "yup" dependency to ease form validation

Relates to
- #298

### CODE REVIEW

**Comment by jeremydthomas** [comment]
@houssamboudiar I can now merge PR's so I'll be looking at this. Please have some patience with me as this is the first time Ive ever done this 😸

**Review by jeremydthomas — COMMENTED** [review]
@houssamboudiar I'm still looking through this, but the first thing I noticed is that you can signup isnt disabled when the form is blank.  So please disable that signup button until all information is added so there isnt any confusion. I see that it does throw errors if you dont put any information in there though.  I'll get back to you when I actually go through the code. First glances look pretty good though, so good job!

**Comment by houssamboudiar** [comment]
> @houssamboudiar I'm still looking through this, but the first thing I noticed is that you the signup button isnt disabled when the form is blank. So please disable that signup button until all information is added so there isnt any confusion. I see that it does throw errors if you dont put any information in there though. I'll get back to you when I actually go through the code. First glances look pretty good though, so good job!

I fixed the issue you mentioned on your previous review, But i had a problem that you might help with !
Email code comes filled with Email value ! But i cant tell which line of code is doing this !

Screenshot from 2022-08-30 18-13-38

**Comment by jeremydthomas** [comment]
> @jeremydthomas if you feel the change is serious enough, then you should run a 'review' and 'request changes' :)

Ok, I'll have to figure out how to do that.

**Comment by jeremydthomas** [comment]
@houssamboudiar Everything else looks good, but I am looking for that bug as well. I havent had luck finding it either, for some reason the email is getting passed to the next form.

**Comment by houssamboudiar** [comment]
> @houssamboudiar Everything else looks good, but I am looking for that bug as well. I havent had luck finding it either, for some reason the email is getting passed to the next form.
> 
> 

I know right ! i checked every line of code it really got me perplexed ☠️ !!

**Comment by jeremydthomas** [comment]
Ive spent quite awhile trying to figure this out, but no luck yet. Ive tried things in here [stackoverflow](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill) but messing with autocomplete doesnt do anything. Maybe turn your inputs into controlled ones like it was before instead of uncontrolled. I really dont know, as I cant find anything that would pass the email value down to the confirmation code. The current one does not do this though and it uses controlled inputs (no real idea if that will make a difference).

**Comment by houssamboudiar** [comment]
> Ive spent quite awhile trying to figure this out, but no luck yet. Ive tried things in here [stackoverflow](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill) but messing with autocomplete doesnt do anything. Maybe turn your inputs into controlled ones like it was before instead of uncontrolled. I really dont know, as I cant find anything that would pass the email value down to the confirmation code. The current one does not do this though and it uses controlled inputs (no real idea if that will make a difference).

I'll try more to figure it out, is there anything else that i can be working on ?

**Comment by jeremydthomas** [comment]
> I'll try more to figure it out, is there anything else that i can be working on ?

Yes, there are 7 other forms that need conversion. Id say you did a pretty good job on this one, its just this one bug we cant seem to find (which is frustrating).

**Comment by houssamboudiar** [comment]
> > I'll try more to figure it out, is there anything else that i can be working on ?
> 
> Yes, there are 7 other forms that need conversion. Id say you did a pretty good job on this one, its just this one bug we cant seem to find (which is frustrating).

I never faced something that "illogical" ... , Yes can you assign me to one of them ?

**Comment by jeremydthomas** [comment]
Looks good! Everything works!

**Comment by mikhael28** [comment]
Great work reviewing @jeremydthomas !

**Comment by jeremydthomas** [comment]
Thanks!

**Pull request merged**
