### PR TITLE
Updatedaboutyou

### PR DESCRIPTION
**Pull request by antonio-b**
@mikhael28  I believe i reduced the state to no unnecessary states being used.

### CODE REVIEW

**Comment by antonio-b** [comment]
@mikhael28  forgive me but I don't really understand what your asking for "toast"  to have context sensitive messages in the catch block.

**Comment by mikhael28** [comment]
I see you currently have two pull requests open - which should I be reviewing?

**Comment by antonio-b** [comment]
@mikhael28  updatedbyyou is the current one to be reviewed. this is the one where i reduced the state.

**Comment by antonio-b** [comment]
correction: updatedaboutyou

**Comment by mikhael28** [comment]
Great, can you close the other PR then? To avoid confusion

**Comment by mikhael28** [comment]
Hi @antonio-b , the first thing I noticed when I pulled up your code was an error message from the create-react-app dev server. 
Screen Shot 2021-09-07 at 9 59 54 AM

There are a couple of other problems in EditProfile.js - again, the most important rule of open-source work is to never submit code that is broken for review.  If the functionality is not fully working, meaning you have not personally tested a) does the name change work b) do all the other bullet points work and c) is the code clean from simple mistakes/formatting errors. If you are using VS Code, you should be seeing some red line underlines, similar to microsoft word, indicating that there is a bug there. Part of this is my fault, the tickets I wrote are perhaps a bit too broad. 

how about we start with just this: why don't we nuke this pull-request/branch, and have you start over on a fresh branch - but this time, let's just focus on making the `languages` drop-down it's own component. We can add the other bits later. You can re-use the code from his pull-request into that code, but let's focus on having a smaller surface area of code to cover. This is a good learning experience for me as a maintainer.

**Comment by mikhael28** [comment]
@antonio-b I've gone ahead and written this ticket up for you, let's get started with this bullet point - and move onto the others after we finish this one!

**Comment by mikhael28** [comment]
https://github.com/mikhael28/paretOS/issues/104

**Comment by antonio-b** [comment]
@mikhael28 Ok, I didn't have any compile errors when i was working on the components. I thought everything was working when i submitted my Pr. I did however know I probably should've started smaller except doing all 4 components before getting the 1st approved. The only issue i was having was on EditProfile.js lines 2-5 where the path of the components was an issue. I did check the functionality but i guess not good enough. I will work on my attention to detail next time. 
git

**Comment by mikhael28** [comment]
The path is just '../components/Languages' - put these new form components into the components folder.

**Comment by mikhael28** [comment]
Sounds good, will look forward to seeing your next PR soon!

**Pull request closed without merging**
