### PR TITLE
fixed the scroll bar on the nav bar for better ui

### PR DESCRIPTION
**Pull request by antonio-b**
Workspace 1_009

My only issue is if/when we add more mentorships, what will it look like.

### CODE REVIEW

**Comment by mikhael28** [comment]
Could you please pull the latest code from the upstream `main` branch? You are missing new code, for example the 1. 2. in the navbar for mentorships has been replaced with an icon. Refer to this: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by mikhael28** [comment]
I don't think we need to remove the nav overflow necessarily, but how can we avoid that ugly view? Because, in Chrome on MacOS - it's not visible. I'm wondering if overflow scrolls are a unique thing only on Linux - can you do some research there?

**Comment by mikhael28** [comment]
Screen Shot 2021-09-03 at 10 23 46 PM
As an aside, this is what the navbar should look like with the latest code. Mentorships are also reworked. Looks better huh?

**Comment by antonio-b** [comment]
@mikhael28 
Supposedly this is an issue with Mac. 
This is the link that i found the information about scroll on Mac vs windows and linux. 

https://kilianvalkhof.com/2021/css-html/you-want-overflow-auto-not-overflow-scroll/

**Showing scroll bars on Mac**
Windows and Linux always show you the scroll bars, but if you’re on Mac you have to change a setting to get them to show. Go to System Preferences, then General and toggle “Show scroll bars” to “Always”.

**Comment by antonio-b** [comment]
Workspace 1_010

I see the difference in the UI and i pulled the upstream so I think my code is up to date. My code doesn't render the Full stack section of the nav bar so that's weird.

**Comment by mikhael28** [comment]
@antonio-b it's not weird, the user you are logged in as does not have access to the Full Stack training. They are a mentor, who does not get that access (unless specified by me). Regardless, the code is looking good. Let me pull down on my machine, confirm, and will merge if ready!

**Comment by mikhael28** [comment]
Awesome, merging in! Great work.

**Comment by antonio-b** [comment]
ok, that sounds great. I thought it was something i was doing wrong. That's good to hear.

**Comment by antonio-b** [comment]
i did however make the same pr under a new branch "nav". I was troubleshooting thinking i didn't have the updated code so that's the reason. Thanks so much. I will introduce myself soon .

**Pull request merged**
