### PR TITLE
Bootstrap to react hook form migration

### PR DESCRIPTION
**Pull request by ivoirh**
Pull-Request for `paretOS`

## Description
- Update SuggestionModal.tsx form to react-hook-form

## Relates to
- #294 

## Reviewers
- @mikhael28

### CODE REVIEW

**Comment by jeremydthomas** [comment]
Not sure how I missed this, I'll look at it later today.

**Comment by mikhael28** [comment]
Hi @ivoirh - thank you so much for sending in this PR. Your PR's code is just a tad behind our up to date codebase, which has recently switched to a different Cognito User pool/APIs for authentication. Logging in is not possible anymore, nor is creating new users - making this hard to test. Everything looks good though, and I'm assuming es-lint and typescript wouldn't let you push broken code so easily - so I'm going to ahead and merge this in! Then, I will test in my main branch to double check that the API requests are still being sent smoothly to the library.

**Review by mikhael28 — APPROVED** [review]

**Comment by mikhael28** [comment]
@ivoirh we have a Discord channel that is reserved for code contributors only - would you like to join? If so, leave an email and I will send you an invite!

**Comment by ivoirh** [comment]
Hello @mikhael28 thank you for answer. Let me know if you find something in my contribution that went wrong. My email is: ivona.irhova@student.tuke.sk, I can join the server if it helps to finish this PR

**Comment by mikhael28** [comment]
@ivoirh just sent you the invite! Talk there.

**Pull request merged**
