### PR TITLE
Initial refactor to TypeScript

### LINKED ISSUE #75: Leaderboard Rework
Right now, our leaderboard component is minimalist but functional. It will sort the users passed in by score, and highlight yourself with a custom color. The boilerplate code we started from also has support for 'order by Name', which frankly is unnecessary. 

There are a few things we want to implement:
1. Remove the references to 'orderByName' and generally simplify/consolidate the code needed for the component to run.
2. Refactor into a Hook
3. Test how the component handles more than 10 users at once - what if you are ranked number 27 out of 34 - should the leaderboard default to your place in the hierarchy? Probably.
4. Update the UI a bit - add an olympic podium of sorts.
5. This leaderboard needs to be slightly flexible, in that we want to be able to perhaps search for a particular member to see their score - maybe a search box is a good thing.
6. We want to be able to pass some props in to modify the purpose/UI of the leaderboard - it needs to be able to be active in a global competition context, a local context or a industry/vertical context.

We first need to run some multi-player tests on the Arena to make sure functionality is still working as it was - then we can dive into making this the world class leaderboard functionality it should be. Our goal should be to make it extensible, for many different purposes.

This qualifies as an 'ownership' ticket.

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

# Pull-Request for `paretOS`

I'm coming back around to the requests to migrate to TypeScript and add Enzyme shallow render tests. Opening as a draft for now so you can review the TypeScript migration, but I'll add some tests soon as well in an additional commit.

## Description
- Initial refactor of leaderboard component to typescript

## Relates to
Fixes #75 

See also #129 for prior discussion!

### CODE REVIEW

**Comment by mikhael28** [comment]
@jayeclark this is looking great! Do you have those shallow render tests by any chance? How is your job search/career transition going? If you have some time, I would like to potentially hire you for some freelance work working in this codebase/open-source project. Interested? Send me an email at `mikhael@hey.com` and we can set up a video call.

**Comment by jayeclark** [comment]
@mikhael28 Thanks for the reminder! I added a few unit tests but didn't go too crazy. It didn't look like unit testing was set up yet for the project, so I didn't want to go too far down the path I was on if I misunderstood the request. 

I'm still finishing up two certs (data science and machine learning), so, not likely job hunting for another few months yet. I'm signing off for the night but I will shoot you an email tomorrow!

**Comment by mikhael28** [comment]
@jayeclark thanks for adding the react-testing-library npm packages! Earlier today, I went through and updated virtually every npm package in the repositorty - the `yarn.lock` was greatly updated! Can you please pull the latest code from upstream `main`, specifically the yarn.lock, and re-install the testing library dependencies and update the PR? Right now, your yarn.lock is showing 22k lines of code change, which makes me think you haven't pulled down the latest.

**Comment by jayeclark** [comment]
Hmm, I pulled & merged latest about 10 minutes before my latest commit…

**Comment by jayeclark** [comment]
@mikhael28 OK I think I resolved it. Still not entirely sure how that 22K diff got in there, but running `yarn install` again and uploading the updated yarn.lock file seems to have fixed it!

**Comment by jayeclark** [comment]
Ohhh, I should be pulling changes from the develop branch (and opening this PR against develop), shouldn't I?

**Comment by mikhael28** [comment]
W00t! Merged in! Will have to put on my to-do list to set up an actual test runner, connect it with GitHub actions. Once a proper 'beta' release is marked, we will set set up a separate prod environment (auth, db instance, etc) and have those environment variables running in the `main` deployment, with the current credentials in `dev`. At that point, discipline in pulling/merging between dev and main will be more important. Anyways, have a great night!

**Pull request merged**
