### PR TITLE
Refactor Leaderboard to use hooks

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

Pull-Request for `paretOS`

## Description
Enhances Leaderboard appearance (leaderboard logic/ranking/score attribution will be addressed in a separate PR.)

- [X] Remove the references to 'orderByName' and generally simplify/consolidate the code needed for the component to run.
- [X] Refactor into a Hook
- [X] Test how the component handles more than 10 users at once - what if you are ranked number 27 out of 34 - should the leaderboard default to your place in the hierarchy? Probably. _(Note: this is set up to default to the user's page in the rankings.)_
- [X] Update the UI a bit - add an olympic podium of sorts. _(Note: Basic podium implemented, styling can be improved in the future. Podium will only display if any participant has a score > 0, podium can be set up to not display ranks of users with null scores)_
- [X] This leaderboard needs to be slightly flexible, in that we want to be able to perhaps search for a particular member to see their score - maybe a search box is a good thing. _(Note: this can be accomplished by using the filter, which now has improved functionality. Unless there is another use case for searching/filtering that I'm not catching?)_
- [ ] We want to be able to pass some props in to modify the purpose/UI of the leaderboard - it needs to be able to be active in a global competition context, a local context or an industry/vertical context. 

Additional improvements:
- [X] Add minor enhancements to existing styling
- [X] Fix hover color for my-rank class to match logo
- [X] Fix padding & font size
- [X] Hide page navigation controls when maxPages = 1
- [X] Fix ranking for identical scores
- [X] Fix rank display for identical ranks
- [X] Carve out PageNavigation and ProfilePic components so they can be used elsewhere in app

## Relates to
Partially addresses #75 

### Screenshots / other info

leaderboard

pagination

### CODE REVIEW

**Comment by mikhael28** [comment]
Hi @jayeclark this looks great, certainly heading in the right direction! What questions can I answer for you?

**Comment by jayeclark** [comment]
@mikhael28 Great! I mainly just wanted the sanity check that the PR is going in the right direction (and that I'd interpreted 'refactor to use hooks' correctly to mean refactoring the class component to be a functional component.)

Do you have an example of the olympic podium feature as implemented somewhere else? If not, no worries, I have a general idea of how to implement (but the styling might not be the exact vision) and can likely find some examples out in the wild.

**Comment by mikhael28** [comment]
I would try to find some examples in the wild - take some inspiration from videogames as well, not just web application UI.

**Comment by jayeclark** [comment]
@mikhael28 The only item I'm still unclear on is the last one. What type of props would be passed to the leaderboard component to modify its appearance? The only thing I can think of is styling, the title, and perhaps the option to toggling the podium, filter bar, and table on or off... the user list is generated prior to being sent to the leaderboard, and everything in the component runs off that, so any changes to the user scope would be decided before the user list is passed to the component. 

Since the last item is pretty open ended (and might not even need to be addressed until the need arises), I'm going to move the rest of the PR to 'ready for review'. It's quite a few changes, so please take your time (and I imagine there will be at least a few changes requested since I'm new to the repo.)

**Comment by mikhael28** [comment]
Sounds great @jayeclark I will review this tonight!

**Comment by mikhael28** [comment]
It looks fantastic from that GIF I see, FYI

**Comment by mikhael28** [comment]
Hey @jayeclark thanks for your patience! I just started a new job and have had my hands full getting onboarded and slangin' some TypeScript. I've taken a look at your PR, and want to compliment you on the work! In particular, I thought it was fun to see you use the `some` Array function, it's been a while since I've seen it in the wild! Great use case for it. 

In general, the code seems sturdy and well-made - I'm going to go ahead and merge it in. If you are up for it and want to be a maintainer for the project, I would ask for two more things for the 'ownership' ticket that will go a long way towards improving the overall repository. The first - is to migrate this component to TypeScript. The second - is to write some simple tests Enzyme shallow render tests, and pre-populate the leaderboard with some realistic mock data. Afterwards, we can take those tests and set up a simple test runner on GitHub through an Action, so that whenever someone sends in a PR - we can immediately understand whether or not it breaks any tests.

**Comment by mikhael28** [comment]
Thanks again for your patience, I'm sorry I couldn't review your PR earlier. I will do a better job of managing expectations moving forward. Would love to work with you more, but I know you are doing the 100 Days of PR challenge (or something like that) - let me know if you have time to do those two other things I mentioned, and if not - let me know if I can help you out in some other way (as a professional reference, for example). If you are open to some freelance work, I might some work for you in mid-December. My email is `mikhael@hey.com` in case you want to chat over email.

**Comment by jayeclark** [comment]
Thanks so much for the feedback & the merge - I’d seen that you started a new job so didn’t want to push about code review… no worries at all on the delay. 

I can definitely work on those two  items,  I feel a lot more comfortable now adding tests vs when I originally opened this PR, and I’m in the middle of wrapping my head around Typescript so that’s a mutually beneficial ask as well. (Though, you’re right, I’m still working on my ‘100 non-trivial PRs in 100 days’ challenge, so I’ll be running a little bit slow on repeat contributions for the next few weeks at least...)

I’ll connect through email about potential freelance work too (I’ll be winding down my challenge in mid-to-late Dec, but won’t be full-time job hunting until the summer.)

**Comment by jayeclark** [comment]
@mikhael28 I haven't forgotten about these requests - I've had family in town and it has made working through my 100 PR challenge _significantly_ more difficult. 😆 I'm working on fleshing out tests for the leaderboard tomorrow and will hopefully open a PR by early next week at the latest.

**Comment by mikhael28** [comment]
@jayeclark sent you a message in the PR you have open!

**Pull request merged**
