### PR TITLE
Landing page login button

### PR DESCRIPTION
**Pull request by mLeoUC**
# Landing.js UI enhancements [#69](https://github.com/mikhael28/paretOS/issues/69)

- [x] Add a secondary button next to SignUp, called Login.
- [x] Add a testimonial from yourself about the app or the open-source community.
- [x] Try to standardize/optimize the CSS a little bit.

### CODE REVIEW

**Comment by LeoHimsef** [comment]
# Landing.js UI enhancements 

- [ ] *Add a testimonial from yourself about the app or the open-source community.*

**@mikhael28 Where do I add the testimonial about the app?**

> ### Before
image

> ### After 
image


```

**Comment by mikhael28** [comment]
@LeoHimsef this is looking great! In terms of adding a testimonial, in `Landing.js` there is a state object called testimonials, and if you scroll down there is a mapping function that is giving you some hints as to the structure of each object in the testimonials array. If you can, write a testimonial object that matches the requirements of the mapping function!

**Comment by mikhael28** [comment]
Leo, would you also be able to add in PropTypes for the Landing component? I think that would be a good idea to do for components/containers moving forward, is to add in PropTypes as we go along. Will make things a bit more maintainable.

**Comment by mikhael28** [comment]
@mLeoUC would you also remove the package-lock.json from the pull-request, and add the package-lock to the .gitignore ?

**Comment by mLeoUC** [comment]
Misha, I was able to add the testimonial, PropTypes and removed package-lock.

**Review by mikhael28 — APPROVED** [review]
Great work! I am now merging your code!

**Comment by mikhael28** [comment]
@mLeoUC I was able to remove the package-lock.json directly from GitHub, how awesome is that? GitHub has just gotten better and better. If you haven't already, please introduce yourself at #17 - and tell us about what's going on in Nigerian tech? Are you in Lagos? Would love to learn more about you, and see how we can localize/integrate with the Nigerian tech community in some way. We have already translate part of the app into Luganda (Ugandan language) and would love to be involved in growing the pan-african tech community.

**Comment by mLeoUC** [comment]
Awesome thanks for merging, been a bit occupied but I have been able to spread out the items on my plate. I'm pretty new to the development on GitHub as well. 

Nigerian tech has been moving rapidly especially fintech where I contribute currently in Lagos. 

I will be glad to help integrate with the community here, but how do you intend to do that? 

Great translate, so are we translating to all languages. I could do Nigeria Pidgin😃.

**Pull request merged**
