### PR TITLE
Improve feature

### PR DESCRIPTION
**Pull request by nikhil12377**
### Changes made

- created a const countries and exported it from `src/libs/static.js`
- created a map function to generate all country names in `src/profile/CreateUser.js`

### CODE REVIEW

**Comment by mikhael28** [comment]
@nikhil12377 please make the small change I requested, and I will merge your code in. Well done!

**Comment by nikhil12377** [comment]
done.

**Comment by nikhil12377** [comment]
i have updated the countries list.

**Comment by mikhael28** [comment]
Great work, merging now!

**Comment by nikhil12377** [comment]
thank you
 i'm looking forward to countribute more.

**Comment by mikhael28** [comment]
@nikhil12377 would you be interested in working on this issue? https://github.com/mikhael28/paretOS/issues/103

**Comment by nikhil12377** [comment]
i'll spend some time understanding codebase then i'll message on issue
.

**Pull request merged**
