### PR TITLE
migrate_to_material_modals

### PR DESCRIPTION
**Pull request by AleksandrKurilov**
Migrate Modal to TS

Pull-Request for `paretOS`

## Description
Migrate component Modal.js to TypeScript

## Relates to
- #87 Migrate away from react-bootstrap modals

## Reviewers
- @mikhael28
- ...
- 
### Screenshots / other info
image

### CODE REVIEW

**Review by mikhael28 — APPROVED** [review]
@AleksandrKurilov on second thought, I'm going to approve this PR for now! Migrating this component to the MUI can be something done later! Now that I've approved this PR, I'm able to invite you to our 'contributor-only' Discord where we can talk about contributing to the project further.

**Comment by mikhael28** [comment]
@AleksandrKurilov lol actually, I cannot merge it in - there is a merge conflict! Can you resolve it please?

**Comment by AleksandrKurilov** [comment]
I've resolved conflict. After merge I will make another PR with MUI.

**Comment by AleksandrKurilov** [comment]
> @AleksandrKurilov on second thought, I'm going to approve this PR for now! Migrating this component to the MUI can be something done later! Now that I've approved this PR, I'm able to invite you to our 'contributor-only' Discord where we can talk about contributing to the project further.

I happy to join your Discord. What it takes to join?

**Comment by mikhael28** [comment]
@AleksandrKurilov what is your email address that you use for Discord?

**Comment by AleksandrKurilov** [comment]
> @AleksandrKurilov what is your email address that you use for Discord?

aleksandrskurilov@gmail.com

**Comment by mikhael28** [comment]
@AleksandrKurilov merged! Sending you an invite now

**Pull request merged**
