### PR TITLE
Chore/remove unused dependencies

### PR DESCRIPTION
**Pull request by jayeclark**
Pull-Request for `paretOS`

## Description
Following up on the discussion on react-native -- this is a dependency in a number of packages (but once the tree is shaken, it has no relevance to the repo.) I resolved it where I could. Also moved react-spring as a dependency to toasted-notes as I assume that package will be phased out eventually in favor of MUI Snackbar or a better toast notifier that has access to context and can consume the MUI theme.

I also found and removed a bunch of unused dependencies and things that were listed as dependencies in the main repo when really they're dependencies of installed packages. Maybe yarn didn't do a good job handling this, pnpm certainly seems to be on top of it. It's down from 30 devDependencies to 25, and from 72 regular dependencies to 49 (though many of those haven't completely disappeared - they're just being installed by the dependencies themselves rather than the main package.json.)

I'm opening this as a draft for now as an FYI - later in the week I'm going to flesh out the test suite and use that as an opportunity to double check that gutting the dependencies really didn't break anything. (So far, so good.)

### CODE REVIEW

**Comment by mikhael28** [comment]
Great work! Make sure to pull the latest changes from main, I've added three dependencies (for the webgl visualization, the music player)

**Comment by jayeclark** [comment]
Yep, will do! I’ll troubleshoot the npm/yarn build issues too. Cannot wait to be done with these interviews this week & get back to building. 😆

**Comment by mikhael28** [comment]
@jayeclark since we have our domain deployment back up and running, I will go ahead and cancel the Vercel builds!

**Comment by mikhael28** [comment]
Rawr GitHub changed Command Enter to close comments/PRs, it's crazy

**Comment by mikhael28** [comment]
Hey @jayeclark , I'm closing this PR because I've gone through it and implemented most of your changes! PNPM deps, Toast context provider, along with a few other tweaks on my end. Details here: https://github.com/mikhael28/paretOS/pull/285

**Pull request closed without merging**
