### PR TITLE
Languageselector migration#297

### PR DESCRIPTION
**Pull request by jeremydthomas**
Pull-Request for `paretOS`

## Description
Updated to MUI select form and react hook form

## Relates to
- #297 

## Reviewers
- @person1 (merge duty)
- @person2
jayeclark or mikhael28, not me!

## Screenshots / other info
image

### CODE REVIEW

**Comment by jeremydthomas** [comment]
Something is off with my prettier or something. My code doesn't look like this on vscode.

**Comment by jayeclark** [comment]
@jeremydthomas What’s the formatting issue you’re having exactly? Maybe I can help. I’ve troubleshot more than a few random formatting issues with VSCode. (The worst was an ‘opinionated’ tailwind class formatter that had opinions that didn’t even make sense and would impose them on any file I opened 😆)

**Comment by jeremydthomas** [comment]
it looked super off on github app on my phone. Usually I just make a .prettierrc every time I make a new branch, but I forgot to do it this time. I never could figure out how to make eslint prettier work with the linter thing. So I just copy the prettier rules out of the .eslintrc.json and stick it in the .prettierrc file

**Comment by jeremydthomas** [comment]
This is how it looked before 

And this is how it looks now.

**Review by mikhael28 — APPROVED** [review]
Great work! Merging it in :D

**Pull request merged**
