### PR TITLE
♻️  refactor(NewSubmitProofModal): converted class component to hooks

### PR DESCRIPTION
**Pull request by akashshyamdev**
Converted class components to hooks based on issue #52. I can't really test this component in the browser because I think you need to pay to get access to this page, so I'd be grateful if you could check it out with a paid account(or give me the credentials to that accounts, for testing). Currently, I've checked through the code and there are no errors with SonarLint(IDE plugin) and CRA(create-react-app). 

Also, I'd like to address this todo on line 33:
```javascript
// @TODO: Is this function repetitive? With Arena proof modal?
```

I think it is repetitive and maybe we refactor the following logic into a utility function/service:

```javascript
let pictureKey = await Storage.put(
        `${this.props.sprint.id}_0_${this.props.day}_${this.props.activeIndex}.${fileType[1]}`,
        file,
        {
          bucket: process.env.REACT_APP_PROOF_BUCKET,
        }
);
```

Finally, I've seen several other class based components so let me know if those need to be converted too. Looking forward to your response :)

### CODE REVIEW

**Comment by mikhael28** [comment]
Good morning @akashshyamdev - you can in fact access this through a 'free' account, this is the Arena functionality. In the Arena, click 'Start a Sprint', select a template, then in competitors - scroll down and select yourself. We have another contributor currently working on improving that experience. Then, pick the Monday the most recently passed. August 30th or whatever. Then click start, then in the Arena home you should see the sprint. Click to see it, and then when clicking 'Submit proof' - you should be able to see the Arena proof modal. Can you confirm that?

**Comment by mikhael28** [comment]
I think refactoring the S3 bucket post into a reusable utility function, with the object name/file as parameters, is a great idea. Can you please do that?

**Comment by mikhael28** [comment]
This is great work so far! Can you do one more thing for me - would you mind using Prettier as your linting extension for this repository? If you look at your commit, it's pretty hard for me and other maintainers to get an idea of what you changed, because almost every single line is green due to linting :)

**Comment by mikhael28** [comment]
@akashshyamdev please let me know if you were able to create the Sprint!

**Comment by akashshyamdev** [comment]
Sorry I just saw your response, for some reason it did not show up in my github feed. Will get to it now.

**Comment by akashshyamdev** [comment]
Ok so I just fixed up the formatting, is it ok now? Also, I'd recommend adding a prettier config to the codebase so everyone's formatting works consistently

**Comment by mikhael28** [comment]
@akashshyamdev I've left two major pieces of code revision necessary for this PR, can you please make them? Additionally, the Prettier config is still not quite what mine is. Can you uninstall Prettier, and other associated Prettier config files/extensions, and then re-install the main one? Then press Command Shift P and run `format document`?

**Comment by akashshyamdev** [comment]
Good Morning @mikhael28. I've reinstalled prettier and followed your steps. Is it ok now? I think the prettier config would be consistent if you add a `.prettierrc` file with your rules. I think you missed what I mentioned about the code revision:

1. Refactoring the image upload function - Where should this function be defined based on your folder structure(in which file)?
2. About the arena proof modal, I was able to successfully create a sprint and see the model - What revision should be done here?

**Comment by mikhael28** [comment]
@akashshyamdev good morning. The answers to your questions:
1. Inside the `src/libs` folder, you can make a `s3.js` file. The `libs` stands for libraries, and in many repositories, is where you will see utility files stored.
2. Refactor into hook, if not already done (I can't remember off the top of my head). Integrate the re-usable S3 bucket function in line 1, just make sure that you are passing in the correct parameters to create the S3 bucket name.
3. For number 3, go look at the commits you have posted in this pull-request - I've left 2 very specific, actionable edits for you to take. After you make those edits, the file should work fine. In reality, you need to solve the 'Paywall Puzzle' in order to gain access to the educational materials to fully test it yourself.
Screen Shot 2021-09-03 at 10 44 47 PM

**Comment by akashshyamdev** [comment]
One thing that comes to mind when having a puzzle to get behind the paywall is cheating. I assume you will have this in production too for actual users, once a guy has solved it, some users may just copy the solution. Have you considered this? Also, I just finished the refactor of the function, I've tested it with ArenaProofModal.js and the upload is working fine:)

**Comment by mikhael28** [comment]
Hi @akashshyamdev thanks for the continued work here! I just tested the arena proof modal s3 upload and it sadly wasn't working for me - here are the steps I took to reproduce my problem.
1. Created a new sprint, with offseason training v3
2. Added myself, and only myself as a competitor (I've just noticed that multiplayer indexing is broken for some reason, going to be working on that today)
3. Created sprint, went into an active day, submitted the proof and the achievement. Achievement successfully registered, and got a notification that the upload worked too. I then scrolled down in the Arena to the 'finished achievements' section, where I clicked the button that said 'Press to See Proof' - when I clicked it, I was taken here. It appears that the key associated with the upload came back `undefined`, when in reality it was supposed to have a UUID assigned by the pictureKey variable in pictureKey. Can you take a look at that?
Screen Shot 2021-09-04 at 9 25 32 AM

**Comment by mikhael28** [comment]
I've gone ahead and opened up a new branch called https://github.com/mikhael28/paretOS/tree/%2352

Can you change the pull-request to be merged into that branch, instead of main?

**Comment by mikhael28** [comment]
I will work on adding a .prettierjs config file. Also, not worried about cheaters - I can always change the puzzle, and plus those people suck anyway. If they think they can cheat their way to learning this stuff, they are wrong. They are only cheating themselves.

**Comment by akashshyamdev** [comment]
Changed base, will address issues tomorrow morning, it's quite late now :)

**Comment by mikhael28** [comment]
Sounds great, talk tomorrow @akashshyamdev

**Comment by akashshyamdev** [comment]
Good Morning @mikhael28, so I just tested this, here's what I get:

Screenshot 2021-09-05 at 10 45 22

I can see the key here, so the function is returning the result.

Steps to reproduce:
1. Created sprint, added myself as a competitor
2. Went down to finished attachment, clicked on submit proof and I see the error you mentioned

I think the issue is not with the function, instead with the see proof part. I think so because the upload is working successfully without errors.

**Comment by mikhael28** [comment]
@akashshyamdev I believe you are correct! Fantastic, I am going to merge your code into branch 52 and take a look myself to see what's going on with the review proof. Congrats on your first merged PR (I believe it's your first?) - thanks for your patience while we go through all of the reviews/edits, it will make both of us better developers.

**Comment by mikhael28** [comment]
@akashshyamdev check out the commit I added in this PR, there were two issues (one mine, another yours) that were quickly fixed to have the functionality fully working :) https://github.com/mikhael28/paretOS/pull/94

**Comment by mikhael28** [comment]
After some more digging, I have gone ahead and disabled the s3 upload for the new submit proof modal. It turns out that we were not saving the file type, as we were in the Arena proof modal - and that, while things did work in the past (somehow), they are not working now. I've gone ahead and disabled it, and am going to re-enable it later. Considering pushing the curriculum data structure revamp much closer in my timeline.

**Comment by akashshyamdev** [comment]
Ok thanks mate 👍

**Pull request merged**
