### PR TITLE
converted JS file to typescript

### PR DESCRIPTION
**Pull request by jeremydthomas**
Pull-Request for `paretOS`

## Description
converted CreateSprintTemplate.js to CreateSprintTemplate.tsx

## Relates to
- #246 
## Reviewers
- @person1 (merge duty)
- @person2

### CODE REVIEW

**Comment by jayeclark** [comment]
@jeremydthomas Thanks for your patience here - I've been AFK for a week or so working on some job interview stuff.

I'm getting a handful of errors when I fire this up locally. (This is what's preventing it from passing CI.) 

It looks pretty straightforward though - there are just some type definitions missing for one of the modules that's used in the file. This can be solved by running `yarn add @types/react-beautiful-dnd`, committing the package.json and yarn.lock changes, and pushing the new commit on the branch up to GitHub (it will update this pull request & then hopefully CI will pass!)
Screen Shot 2022-05-27 at 12 02 59 PM

The compiler is complaining about implicit any's on lines 301, 319, 338 - but these are all related to the drag-and-drop module and will resolve automatically when those types are added.

**Comment by jeremydthomas** [comment]
Well, I hope this works as I had trouble after adding in all of the new things misha added.

**Comment by jayeclark** [comment]
@jeremydthomas Yeah, let me merge in my PR fixing the CI (I’m on my phone right now but I’ll do it first thing in the morning) … I think CI should pass after I do that! Fingers crossed. :)

**Comment by jeremydthomas** [comment]
Sounds good @jayeclark , is that why I got that --env error when trying to run the test script?

**Comment by jayeclark** [comment]
@jeremydthomas Yep, exactly! I had to install and set up a new testing suite (vite-jest) that works with Vite, the old test scripts got broken by the switch. :)

**Pull request merged**
