### PR TITLE
ui suggestion for ExperienceSummary.js

### PR DESCRIPTION
**Pull request by antonio-b**
changed the active component background color. changed the background color, and color when component is hovered.

### CODE REVIEW

**Comment by mikhael28** [comment]
@antonio-b would you do me a favor and make a comment on this pull-request with a screenshot of what it looks like?

**Comment by antonio-b** [comment]
Workspace 1_002

when hovered
Workspace 1_005

**Comment by antonio-b** [comment]
I just realized ExperienceSummary.js shoudn't have any edits. I left white space unintentionally.

**Comment by mikhael28** [comment]
@antonio-b those look fantastic - would you mind changing the hover color to the same green the buttons are? After that, I will go ahead and merge in the code! Please include a screenshot of the green!

**Comment by antonio-b** [comment]
Yes, will do. thanks

**Comment by mikhael28** [comment]
Introduce yourself here after your next commit! https://github.com/mikhael28/paretOS/discussions/17

**Comment by antonio-b** [comment]
Workspace 1_007

**Comment by antonio-b** [comment]
Workspace 1_008

Correction: this is the right color. previous commit was color of the hover color and not active color.

**Comment by mikhael28** [comment]
Alright @antonio-b I've merged in your code! How does it feel - was that your first open-source PR that was merged in? I really like that you are using Ubuntu, I think that will be really helpful for us - one thing I've noticed in your browser, that I haven't seen anywhere else - probably because its on Ubuntu - but on the LeftNav, on the part below 'Mentorships' where it says 1. Aurelien Garbarz and 2. Mikhael there are those very visible and ugly scroll indicators. Would you be able to write up a ticket in the Issues section, and working on removing that Ui eye-sore for your next pull-request?

**Comment by mikhael28** [comment]
You are a don, thank you! Happy to see your first PR was here, I hope you will have many more over the course of your career :D

**Pull request merged**
