### PR TITLE
Competitor Search and Delete

### PR DESCRIPTION
**Pull request by wesley3295**
Used datalist and made a button to delete competitor from state array

### CODE REVIEW

**Comment by mikhael28** [comment]
Screen Shot 2021-09-03 at 5 46 21 PM
Got this first error when I tried to type a name into the search box, but decided to cancel. I think it might have happened before the players finished loading in the initial fetch request. Can you replace the search box with a loading placeholder, so that users don't click on it before it's done loading.

Once it loads, it seems to do a great job searching and adding players. The red x seems to work well in removing players.

As a piece of feedback, would you please put the search box below 'Choose your competitors'?
Screen Shot 2021-09-03 at 5 48 41 PM

Would you also change the 'Template' into the the same data-list format, with the same CSS as the new form for styling consistency? I like how the search box is nice and short, whereas the form for the template stretches across the whole screen.

Great work so far! What do you think of semantic html search, pretty awesome huh? I think that's a trend we will see moving forward, HTML getting more and more powerful, replacing JS for some essential functionality like that.

**Comment by mikhael28** [comment]
Also, make sure to pull the latest changes from remote main branch before you submit any PR - that way, you are making sure you aren't creating any accidental merge conflicts with the most up to date code! Let me know if you have any questions about that.

**Comment by wesley3295** [comment]
Yea I might need a little guidance on the pull request? Sorry, this is my first time really utilizing GitHub and I don't want to screw the code up by pulling the wrong thing. 

I think I completed the ticket though, just need to implement user into redux so we can add them automatically into players local state. I also did a select search for the missions, because with the option of all users able to create a sprint template you might want a search. I'm not sure if you're okay with this but I disabled the inputs for missions and players until the promise came back. I would need more guidance on how to implement a loading screen to a datalist select menu. I've read that datalist are close to impossible to style. It might be out of my knowledge.

**Comment by mikhael28** [comment]
This is the link that I think will describe the process of pulling from my upstream repository the best. https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by mikhael28** [comment]
Yes, I definitely appreciate you disabling the forms until the promise is returned - that's exactly what d was looking for. Will need to check implementation once you send the next commit. 

And yes, please save the user into redux, then auto add them to the teams, then filter yourself out of the list of available teams. Also, whenever a player B is selected, make sure you filter them out too, if they haven't been already.

**Comment by mikhael28** [comment]
Any questions for me about this feedback?

**Comment by wesley3295** [comment]
Just lost all my work from merging... 
:(

**Comment by wesley3295** [comment]
fixed it, but I need to find out how to merge without overwriting my work

**Comment by wesley3295** [comment]
Can you tell me what file would be best to store our user in redux? I was thinking App.js?

**Comment by mikhael28** [comment]
Good idea creating a new PR! This one was getting a bit messy. The place to store application state is going to be in the 'state' folder.

**Pull request closed without merging**
