### PR TITLE
Add more tests to leaderboard component

### PR DESCRIPTION
**Pull request by neilgebhard**
Hi @jayeclark, I was wondering if these tests are similar to what you're looking for.

I must mention that there is an issue with one of the tests so far. The input for filtering the leaderboard doesn't seem to accept values. I tried using fireEvent.change to add a value to the input. (You can see how I wrote the test.) In theory, it should work. I'll try to debug it

## Description
- Added some tests for the table in the Leaderboard component

## Relates to
- #150

### CODE REVIEW

**Comment by jayeclark** [comment]
Hey @neilgebhard I'll review in detail this evening, but at first glance - yes! - these are exactly the type of tests we were hoping to have built out for the component!

Also - oh man, I have struggled with that exact same input issue in the past. I know exactly what you are talking about and it was super annoying to deal with! If I happen to remember the steps I took to resolve it (or the repo I was working on when I encountered with it), I'll circle back around and give some suggestions.

**Review by mikhael28 — CHANGES_REQUESTED** [review]
@neilgebhard these tests look great! I was wondering if we could ask you to do one more thing - set up a central test suite. As you may have noticed, our project currently has basically 0% test coverage, which we are certainly looking to change. However, there is no central `yarn run test` command which will kickoff all of the tests in our project, in an organized manner - that could also allow for conditional pass/fail GitHub Actions that are triggered when a PR is sent in.

Would you mind moving the Leaderboard test file into a central  `test` folder, and connect that to a central `yarn test` command?

**Comment by neilgebhard** [comment]
Hi @mikhael28, thanks for the feedback. I tried to make the changes you requested. I put a `test` folder inside `src`. Is there anything that needs to be done to connect it to a central `yarn test` command? Running `yarn test` seems to [find any files in the project with a `.spec.tsx` suffix and run them](https://create-react-app.dev/docs/running-tests/#filename-conventions)

**Comment by mikhael28** [comment]
Perfect! Thank you @neilgebhard , merging your code in!

**Comment by neilgebhard** [comment]
Awesome 😊

**Pull request merged**
