### PR TITLE
feat: ContextBuilder - Implement hooks

### LINKED ISSUE #42: ContextBuilder - Refactor to Hook from Class
In `src/context/ContextBuilder` we want to refactor the Context Builder component from a class into a hook. This ticket is reserved for @Chris-isCoding - so, let's give him 72 hours to respond to this ticket (meaning, confirm that you are working on it). He sent me an email earlier today asking for specific guidance, so this is the result of that.

### PR DESCRIPTION
**Pull request by Chris-isCoding**
## Changes Made

 - Refactor Class component to function component
 - Use React.Children so indices are not used as keys for map method

closes #42

### CODE REVIEW

**Comment by mikhael28** [comment]
Hey @Chris-isCoding , way to get this done quickly! You know, I rarely if ever use the React.Children API - I was wondering, 'why did he do that'? I went down a bit of a rabbit hole, and learned some good stuff - mostly that it's great when you are trying to create a flat array, and maintain the original key of the nested arrays inside the `children` prop. This article is long but interesting: https://www.smashingmagazine.com/2021/08/react-children-iteration-methods/

You learn something new everyday! Can you explain in your words why you chose to implement this pattern? Perhaps you know something I don't :) Either way, everything works, and I am merging your code! Congratulations!

**Comment by Chris-isCoding** [comment]
Hey @mikhael28 

Thank you sharing the link. That's a first time I used React.Children API - my main reason was that the indices shouldn't be used as keys for map method. It is anti-pattern and should be avoided.

https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318#.6nz2tbgsw

I could have used id as a key but I wasn't quite sure why it wasn't used previously and I was unaware that MongoDB uses underscore for built-in identifier.

```javascript
key={topic._id}
```

I am looking forward to deepen my knowledge and learn with you all.

**Comment by mikhael28** [comment]
Ah I've actually read this article in the last few weeks, it was quite good. They are definitely right, we should not be using index's as keys. However, there are exceptions to the rule:
```Update: Exception from the rule
Many people asked if they always, always have to generate ids. Others have suggested use cases when using the index as a key seems justifiable. It is true that sometimes generating new ids is redundant and may be avoided. For example translation of license terms or list of contributors. To help you decide, I put together three conditions which these examples have in common:
the list and items are static–they are not computed and do not change;
the items in the list have no ids;
the list is never reordered or filtered.```

I believe with this **specific** component those three exceptions are met, but you have given a great callout! We need to refactor a lot of our mapping functions to use ids instead of indices, a definitely anti-pattern

Also, you are right (again!) - perhaps I should have used the _id pattern in Mongo. That CAN be done... but will require essentially a large scale reset of the entire application. We can probably do that when we run 'The Great Migration' once we move out of alpha into beta.

**Comment by mikhael28** [comment]
@Chris-isCoding introduce yourself in our 'Discussions' thread!

**Comment by Chris-isCoding** [comment]
Thanks @mikhael28 for your insight and true, in this case it could probably be avoided but I wanted to be on the safe side.

In regards to the `._id` it is present, I haven't used Mongo DB before but I console.log(topic) and it's there as it is as  mentioned built-in identifier. I was trying to use `id` previously and it wasn't working but that was before I did research on Mongo DB and underscore.

**Pull request merged**
