### PR TITLE
TabPanel Component

### PR DESCRIPTION
**Pull request by wesley3295**
I took out your Typography Material-ui component in ContextBuilder.js. It wasn't doing anything from what I saw. I left it commented out if you ever want to add it back in. I cant test Sprint, but I know it works for ContextBuilder.js

### CODE REVIEW

**Comment by mikhael28** [comment]
Hey Wesley, thank you for getting started on this. I'm curious though - why can't you test sprint? This is a great chance to get a better idea of how new users are approaching the Arena, and what UX improvements are needed. Is there a bug? Is it confusing?

**Comment by mikhael28** [comment]
We really should have a singular component that addresses both use cases - I agree though, if it looks better without the Typography, that's great! Would you mind posting two screenshots, one with Typography and one without? That way I (and others) can see exactly what you mean!

**Comment by wesley3295** [comment]
With Typog
with typography
Without Typog
without typography

Yea I understand making a component that could address the use case, but I don't think you necessarily want anything there unless it's CSS related. Small change in cards with typography, honestly Lead Dev's choice.

I signed up and got into Create Sprint, but I have no idea how to navigate to "/arena/sprints/:id" after creating a sprint. I could type it in, but I have no idea what the id of my Sprint is. Where is the link or button to observe the sprint show page?

**Comment by mikhael28** [comment]
There should be a card in the 'Arena' section, to the left of the chatroom? 
Screen Shot 2021-08-30 at 7 37 04 PM
Can you send me a screenshot of your home page?

This is likely what happened - you created a sprint, selected a template, but didn't select yourself as a competitor - and thus are not registered on that team. I'm going to write up a ticket for that right now, would you be interested in working on that? Basically, when creating a sprint, you always automatically set yourself as a competitor and then remove yourself from the list of competitors.

**Comment by mikhael28** [comment]
Regarding THIS pull-request, I will happily accept the change - I don't see a difference in Typography vs no Typography, but I believe you. Would you please remove the commented code, and just leave the import of the component? Then I will go in and test, and merge if nothing is broken :)

**Comment by wesley3295** [comment]
Yes, I'm currently on my way to bed, but seems like an easy fix for the Sprint, I'll take a look at it tomorrow, and I'll clear the Comments tomorrow.

**Comment by mikhael28** [comment]
Good morning @wesley3295 would you take a look at this ticket I just cooked up? I think it would be fantastic if you could work on this, a great (and needed) contribution. https://github.com/mikhael28/paretOS/issues/46

**Comment by wesley3295** [comment]
I deleted the comments in the TabPanel, I just pushed the commits. Ill take a look at #46

**Comment by mikhael28** [comment]
@wesley3295 that is fantastic, I've gone ahead and resolved that little merge conflict and merged your code in! Can you introduce yourself in our 'Discussions' page, in the 'New Contributor Discussions' thread?

**Pull request merged**
