### PR TITLE
ContextPage component refactor

### PR DESCRIPTION
**Pull request by frankykubo**
Pull-Request for `paretOS`

### Little design updates:
The header of Context page, especially the elements "Suggest new resource" and "Read overview" looked like plain text. I decided to enliven it a little. Suggest new resource button by adding outline and subtle background on hover, read overview by adding pointer cursor for better UX and also opacity on hover. (Below is before after image)

Because of hover styles, I made a new file @/css/buttons.css and imported it in index.jsx.

### Code refactor:
In this refactor, I was trying, where possible, to use ES6 and newer syntax, with arrow functions, single-line conditions...
I was able to lessen component's lines of code by ~100. So before, it was 570, after refactor, it is 472.

## Relates to
- #156

## Reviewers
- @mikhael28 
- @jeremydthomas 

## Screenshots / other info
**Before:**
original

**After (no hover)**
normal

**After (hover)**
hover

### CODE REVIEW

**Comment by jeremydthomas** [comment]
@frankykubo this might be a bit above my paygrade, Ill let misha the owner look at it.

**Comment by frankykubo** [comment]
@mikhael28 Hello, it has been a while. Is there any chance of accepting the pull request? It would really help me getting a better grade in my exams.

**Comment by jeremydthomas** [comment]
> @mikhael28 Hello, it has been a while. Is there any chance of accepting the pull request? It would really help me getting a better grade in my exams.

I havent seen him in awhile, if he doesnt respond here soon, I'll take a look at it to help you out.

**Comment by frankykubo** [comment]
Hello @jeremydthomas , it has been a while. Is there a way you can help me? Thank you!

**Pull request closed without merging**
