### PR TITLE
fix: remove all unnecessary scrolls

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
Pull-Request for `paretOS`

## Description
Remove all unnecessary over-scroll.

## Relates to
- #170 

## Reviewers
- @mikhael28 
- @jayeclark 

## Screenshots / other info
Example of one of the affected pages

**Before**

Screenshot (402)_LI

**After**

Screenshot (403)

### CODE REVIEW

**Comment by mikhael28** [comment]
Hey @Olaleye-Blessing , thank you for sending this in. I'm going to take a closer look at this tomorrow - my immediate feedback, is that we have included a LOT of !important tags, which are kind of an anti-pattern in CSS. I'm going to pull this down on my machine and take a look - though I think the padding might be worth adding the !important tag.

**Comment by Olaleye-Blessing** [comment]
I also frown at using *!important* but I have no choice here.
I think @jayeclark said the issue is from the bootstrap modal.

**Review by mikhael28 — APPROVED** [review]
Great work @Olaleye-Blessing - I've pulled this down on my machine, and also download Firefox so I can see what you see. Everything looks great to me, merging in!

**Comment by mikhael28** [comment]
I'm a little concerned about all the !important tags, but we can clean that up in the future.

**Pull request merged**
