### PR TITLE
'Removed Glyphicon and added react-icons to EditProfile'

### PR DESCRIPTION
**Pull request by jeremydthomas**
Pull-Request for `paretOS`

## Description
Updated EditProfile.js by removing import Glyphicon from "react-bootstrap/lib/Glyphicon"
 Added import { BsPencil, BsPlusLg } from "react-icons/bs";

Removed the Glyphicon Pencil mentions and added BsPencil, while trying to make it look better.
Removed the Glyphicon Plus mentions and added BsPlusLg, while lining it up to BsPencil and tried to make it eye pleasing.

## Relates to
- #179 

## Reviewers
- @person1 (merge duty)
- @person2
- ...

## Steps to reproduce (if describing bug fix)
- Start project
- Make request to `/endpoint` with `{ "body": "test" }`
- Expect some response

### Screenshots / other info
...
image

some other info, while making my changes, I noticed that clicking on the projects plus sign i get this error.

image
so, I discarded my changes thinking it was me who did it. However, the error is still there.

### CODE REVIEW

**Review by mikhael28 — APPROVED** [review]
Approved! Congrats, is this your first open source PR? For that bug that you noticed, can you please post that screenshot/text and create an Issue, and leave a 'bug' label? Perhaps that can be your next tasks, logging and understanding why that might be breaking.

**Comment by jeremydthomas** [comment]
@mikhael28 yes it's my first "real" PR, the other ones I had were from open source how to discord channels and such. I'll try to do that last one you had in #179

**Comment by mikhael28** [comment]
@jeremydthomas can you post some links as to what Discord channels these were? They seem like a cool resource.

Sounds good, good luck!

**Comment by jeremydthomas** [comment]
[eddie hub](https://www.eddiehub.org/?r_done=1)

Eddie hub is the most active, best one I found, His discord link is on his page there. The other discords I was in kind of sputtered out, to no activity any more.

**Comment by mikhael28** [comment]
Rock on, thanks for the link! What are your goals in JavaScript land - what are you trying to accomplish?

**Comment by jeremydthomas** [comment]
Well, originally I was looking at doing a career change. Now, I'm having so much fun doing this, it doesn't even matter to me if I actually get a job or not as I will continue with this open source path either way. My goals are to get proficient enough in js that I feel confident enough to tackle some of these bigger projects I see that dont have the beginner or good 1st issue tag.

**Comment by mikhael28** [comment]
That sounds great! As you can tell in our repository, we have various levels of difficulty/ownership for the issues - there are plenty to choose from. If you have any suggestions for things/functionality to add, open up an Issue and let's discuss it.

One more thing - we have a contributor only Discord channel, would you like to join? If so, please leave your email here

**Comment by jeremydthomas** [comment]
@mikhael28 tommyhilfiger12@hotmail.com, discord sounds great

**Comment by mikhael28** [comment]
Invite sent!

**Pull request merged**
