### PR TITLE
Fix websocket connection recursion

### LINKED ISSUE #3: WebSocket Connection 'Ping' Creating New Connections
Currently, AWS Websocket connections to API Gateway will close in 10 minutes, if there is no activity. To attempt to counter this, I have put in some 'reconnect' logic, that you can see in `App.js` mostly between lines 237-326 in React. The problem may be somewhere there, but more likely the culprit is in the web socket connection API - instead of creating a new connection ID, things should simply be 'pinging' the web socket, keeping the connection open.

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

Pull-Request for `paretOS`

## Description
Refactors WebSocket to /libs and prevents subsequent connectSocketToSprint calls from creating new connections. 

## Relates to
- Fixes #3 

## Reviewers
- @mikhael28 

### Screenshots / other info
Stable code from #194

### CODE REVIEW

**Comment by jayeclark** [comment]
Integration test passing locally, but not on CI - I'm investigating! Also not sure why it takes 23 seconds to sign out.... 🤔 

Screen Shot 2022-04-16 at 2 24 10 PM

**Comment by jayeclark** [comment]
Update: this _might_ be being caused by an intermittent issue connecting to m.stripe.network and not actually be caused by my code --- my local development server today is occasionally getting stuck in infinite loading mode waiting that resource. 

Might be messing with the "waitForNavigation()" method. Tests are occasionally failing locally for me now as well for the same reason now as they are in the CI pipeline.

**Comment by jayeclark** [comment]
Converting to draft while I focus on troubleshooting the CI pipeline… current logic will cause the tests to time out because a fresh login takes so long to load and the test runners are sometimes fairly slow. (Fiddling on a new branch in my fork, I’ve been able to reduce login/first load time from 14-15 seconds down to around 5 seconds. Can probably get it lower if we use skeletons on the routes. So I’ll probably do *that* PR first to prevent the tests from failing due to timeouts.

**Comment by mikhael28** [comment]
Thank you for your persistence here - odd to hear about the Stripe library timing out like that. It IS fairly old... I'm not even sure that react-stripe-elements library is even actively supported anymore, something to look into for me. Let me know if there are any updates on that specific package, and whether we might want to disable that for the time being (the functionality is mostly lying dormant at the moment anyway).

**Comment by mikhael28** [comment]
I saw this from Stripe a few days ago: https://link.co/
I also think this is likely a better long term solution: https://stripe.com/payments/payment-links

Context: right now, I have a course that I created, that I have a stripe link setup for on the OS. However, in our backlog, we would like to create an extensible education system where anyone can create their own course, with their own achievements and corresponding ability to accept payments. Using something like Stripe payment links is a good solution, because the course creator can use it to accept payments, and they can deploy a Webhook/we can deploy a webhook that ties into it, which would unlock premium courses for people on the platform. People could also create free courses. 

There is... a lot to consider for such a system. My main point though, is that if the Stripe library is making our life difficult - let's remove it (and comment out imports in the system that use it, the BillingForm components) and think more about what we want to do long term.

**Comment by jayeclark** [comment]
I’ve been experimenting some more, and even after rewriting the test to not wait for absolutely all content to load (an escape route for the endlessly loading Stripe script), there seems to be a recursion/race condition or something in the state management that can cause incredibly long initial loading times before the load screen drops (like 30-50 seconds) while some of the same data gets reloaded - it’s better if the data is already in localStorage but even then it’s still pretty long.

**Comment by mikhael28** [comment]
Do you think perhaps running both 14.x and 16.x tests at the same time might be the issue? Maybe we can just run 16.x? Are they running synchronously, asynchronously or does GitHub's test runner maybe use multiple cores in Java or something to operate this and that could be creating a race condition of sorts? I'm probably babbling, just offering some thoughts.

**Comment by mikhael28** [comment]
Amplify/Cognito is a bit notorious for having bad login times on unoptimized systems - I've been working with Cognito in Flutter in my work, and they only recently published a fix for the web build bringing the login times <10 seconds. See 2.0 changelog

**Comment by jayeclark** [comment]
I don't *think* so, based on the error message, but who knows. 

I've got it working a _lot_ better on my local fork. [https://github.com/jayeclark/_paretOS/actions]( https://github.com/jayeclark/_paretOS/actions) Going to clean up the code a little bit more and open a PR shortly.

**Comment by mikhael28** [comment]
This makes me so sad

**Comment by jayeclark** [comment]
God that API bundle -- what TF is it doing that it needs to be so big?! I must be missing something. 

I *thought* I saw something about being able to only import the RestAPI (and skip GraphQL) to reduce bundle size, but of course now I can't find it in anywhere the docs. AWS! (shakes fist)

**Comment by jayeclark** [comment]
There is a rest-only library, it looks like... about half the size unpacked.

[https://www.npmjs.com/package/@aws-amplify/api](https://www.npmjs.com/package/@aws-amplify/api)

[https://www.npmjs.com/package/@aws-amplify/api-rest](https://www.npmjs.com/package/@aws-amplify/api-rest)

**Comment by mikhael28** [comment]
@jayeclark more than 50% smaller! https://bundlephobia.com/package/@aws-amplify/api-rest@2.0.38

Sweeeeet!

**Comment by mikhael28** [comment]
Screen Shot 2022-04-18 at 10 11 02 AM
The hilarious thing is that the REST-API package is already importing Cognito as a dependency... so the two packages could likely be combined into one that doesn't force you to pull your hair out.

**Comment by mikhael28** [comment]
I honestly have no idea wtf Amplify is thinking with their packages, they are making packages used by tens of thousands, hundreds of thousands of devs, and it just feels like they don't care that much about bloat.

**Pull request closed without merging**
