### PR TITLE
Nigerian pidgin localization

### PR DESCRIPTION
**Pull request by leouonline**
Pull-Request for `paretOS`

## Description
Updated
- [x] src/components/LeftNav.js
- [x] src/profile/EditProfile.js
- [x] src/libs/strings.js

## Relates to
- #121 

## Reviewers
- @person1 (merge duty)
- @person2
- ...

## Steps to reproduce (if describing bug fix)
- Start project
- Make request to `/endpoint` with `{ "body": "test" }`
- Expect some response

### Screenshots / other info
...
image

### CODE REVIEW

**Review by LeoUCon — COMMENTED** [review]
LGTM

**Comment by mikhael28** [comment]
@LeoUCon this looks great! One thing though - can you please remove the yarn.lock that you pushed, and add that to your .gitignore ? You didn't add any npm/yarn dependencies, so there is no reason for your yarn.lock to be pushed up :)

**Review by leouonline — COMMENTED** [review]
@mikhael28 WDYT

**Comment by leouonline** [comment]
What do you think?

**Comment by mikhael28** [comment]
Hi @leouonline sorry to ask, but I noticed that you added an update to TypeScript which updated the yarn.lock - and also removed the`package-lock.json` from the .gitignore

Would you mind reverting the changes? We want to keep the `package-lock.json` in the .gitignore (AND the Amplify folders) but also please keep the `yarn.lock` in the .gitignore. Thank you!

**Comment by leouonline** [comment]
Hi @mikhael28 Guess we good to go? 

Please feel free to drop in any modification that still needs to be done. Thank you!

**Comment by leouonline** [comment]
Hey @mikhael28, just checking in to see if there is something I need to update here

**Comment by mikhael28** [comment]
@leouonline I've gone ahead and merged in the code! Thank you for adding the translation - the only thing would be, in the future, to add back language option to the dropdown in the `Languages` component, that we recently spun off into it's own component.

**Pull request merged**
