### PR TITLE
Improve feature

### PR DESCRIPTION
**Pull request by nikhil12377**
Pull-Request for `paretOS`

## Description
- Added hindi language.
- From line 1355 to 1532.

## Relates to
- #112

### CODE REVIEW

**Comment by nikhil12377** [comment]
@mikhael28 I have translated up to _marketing descriptions_.

**Comment by mikhael28** [comment]
This is fantastic, thank you @nikhil12377 ! One thing - would you please review the localization pull-request by @CoDigo93 for adding portugese-brazilian? https://github.com/mikhael28/paretOS/pull/106/files Do you see how he added a dropdown option in `LeftNav.js` and added a default language option in `EditProfile.js` - would you please do the same for the Hindi localization?

**Comment by nikhil12377** [comment]
Sure.

**Comment by nikhil12377** [comment]
- Added MenuItem for hindi language in `LeftNav.js`.
- Added hindi option in `EditProfile.js`

**Comment by mikhael28** [comment]
Excellent work @nikhil12377 ! Merging this in :D

**Pull request merged**
